server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
      #          configurando o redirecionamento da rota do loadBalance
      routes:
        - id: cambio-service
          uri: lb://cambio-service
          predicates:
            - Path=/cambio-service/**
        - id: digital-library
          uri: lb://digital-library
          predicates:
            - Path=/digital-library/**
        - id: openapi
          uri: lb://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
